---

rest_listen_uri: http://127.0.0.1:9000/api/
web_listen_uri: http://127.0.0.1:9000/
web_endpoint_uri: http://127.0.0.1:9000/api/

# You should change these defaults for security reasons.
graylog_password_secret: Gahfoh1ooqu9toxai8lah2xingooVohgae1aorich7faengaJaegh8yaeNgeeT0eiNgohs9phais6phae8Chahpoogho5aic
graylog_root_password_sha2: 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8

# MongoDB Config
## Package
mongodb_version: 3.4.14
mongodb_major_version:    "{{ mongodb_version.split('.')|first }}"
mongodb_minor_version:    "{{ mongodb_version.split('.')[1] }}"
mongodb_repo_version:     "{{ mongodb_major_version }}.{{ mongodb_minor_version }}"
mongodb_apt_repo:         "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_repo_version }} multiverse"
mongodb_yum_repo_baseurl: "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongodb_repo_version }}/x86_64/"
mongodb_signing_key_url:  "https://www.mongodb.org/static/pgp/server-{{ mongodb_repo_version }}.asc"


mongodb_service_name: mongod
mongodb_user: mongodb
mongodb_group: mongodb
mongodb_packages:
  - "mongodb-org={{ mongodb_version }}"
  - "mongodb-org-server={{ mongodb_version }}"
  - "mongodb-org-shell={{ mongodb_version }}"
  - "mongodb-org-mongos={{ mongodb_version }}"
  - "mongodb-org-tools={{ mongodb_version }}"
#bindIp: 127.0.0.1 # TODO: Remove when done testing
mongodb_port: 27017
mongodb_dbpath: /var/lib/mongodb
mongodb_logpath: /var/log/mongodb/mongod.log
mongodb_storage_engine: "wiredTiger"
mongodb_journal_enabled: true
mongodb_profiling_threshold: 100
mongodb_profiling_mode: "off"
mongodb_enable_localhost_auth_bypass: true
mongodb_is_arbiter: false
mongodb_authorization_enabled: false
