---

rest_listen_uri: http://127.0.0.1:9000/api/
web_listen_uri: http://127.0.0.1:9000/
web_endpoint_uri: http://127.0.0.1:9000/api/

# You should change these defaults for security reasons.
# If running multiple servers, this secret should be the same for all of them.
graylog_password_secret: Hw3R5xMCSv7sAdhjjNFL0qhbMkD4avrVIPvW0cwHSok077GG5R22fFvXujCd9pBcJTSYYMufb8bOtzQh2J2rH4ExFYD5nOMi
# The default user is "admin" and the default password is "password".
graylog_root_password_sha2: 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8


# TODO: There was an issue parsing these vars. Fix them and use them to install graylog and elastic search
# Graylog Config
## Package
# graylog_version: 2.4
# graylog_apt_repo: "https://packages.graylog2.org/repo/packages/graylog-{{ graylog_version }}-repository_latest.deb"

# ElasticSearch Config
## Package

# Graylog 2.4 does run with elastic search 6.x.
# See http://docs.graylog.org/en/latest/pages/installation/operating_system_packages.html
# for details.
# elasticsearch_version: "5.x"
# elasticsearch_apt_repo: "https://packages.elastic.co/elasticsearch/{{ elasticsearch_version }}/debian stable main"

# MongoDB Config
## Pip
pip_download_dest: /tmp
pip_version:
python: python
pip: pip

## Package
mongodb_version: 3.4.14
mongodb_major_version:    "{{ mongodb_version.split('.')|first }}"
mongodb_minor_version:    "{{ mongodb_version.split('.')[1] }}"
mongodb_repo_version:     "{{ mongodb_major_version }}.{{ mongodb_minor_version }}"
mongodb_apt_repo:         "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_repo_version }} multiverse"
mongodb_yum_repo_baseurl: "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongodb_repo_version }}/x86_64/"
mongodb_signing_key_url:  "https://www.mongodb.org/static/pgp/server-{{ mongodb_repo_version }}.asc"


mongodb_service_name: mongod
mongodb_user: mongodb
mongodb_group: mongodb
mongodb_packages:
  - "mongodb-org={{ mongodb_version }}"
  - "mongodb-org-server={{ mongodb_version }}"
  - "mongodb-org-shell={{ mongodb_version }}"
  - "mongodb-org-mongos={{ mongodb_version }}"
  - "mongodb-org-tools={{ mongodb_version }}"

# Bind the mongodb so that it is only accessible from localhost. Only useful if all services are running on the same host.
#mongodb_bind_ip: 127.0.0.1
mongodb_site: 'localhost'
mongodb_port: 27017
mongodb_dbpath: /var/lib/mongodb
mongodb_logpath: /var/log/mongodb/mongod.log
mongodb_storage_engine: "wiredTiger"
mongodb_journal_enabled: true
mongodb_profiling_threshold: 100
mongodb_profiling_mode: "off"
mongodb_is_arbiter: false

# Allows an auth bypass to create the first user in the db
mongodb_enable_localhost_auth_bypass: true
mongodb_authorization_enabled: true

mongodb_user_admin_name: 'admin'
mongodb_user_admin_password: 'password'

mongodb_graylog_username: 'grayloguser'
mongodb_graylog_password: 'password'

authenticated_mongodb_connection_uri: "mongodb://{{ mongodb_graylog_username }}:{{ mongodb_graylog_password }}@{{ mongodb_site }}:{{ mongodb_port }}/graylog"
unauthenticated_mongodb_connection_uri: "mongodb://{{ mongodb_site }}:{{ mongodb_port }}/graylog"
